site_name: Akismet for Yii
site_description: Akismet connector for Yii, high-performance PHP framework.
site_author: Cédric Belin - cedric@belin.io
site_url: https://docs.belin.io/yii2-akismet

docs_dir: ../doc
site_dir: ../www

repo_name: git.belin.io
repo_url: https://git.belin.io/cedx/yii2-akismet
edit_uri: ""

copyright: Copyright &copy; 2016 - 2020 Cédric Belin
extra:
  social:
    - icon: fontawesome/solid/globe
      link: "https://belin.io"
      name: Belin.io
    - icon: fontawesome/brands/github
      link: "https://github.com/cedx"
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/cedxbelin"
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/cedxbelin"
      name: LinkedIn

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Features:
      - Key verification: features/key_verification.md
      - Comment check: features/comment_check.md
      - Submit spam: features/submit_spam.md
      - Submit ham: features/submit_ham.md
  - Further reading:
      - Events: advanced/events.md
      - Testing: advanced/testing.md
  - About:
      - Changelog: about/changelog.md
      - License: about/license.md
      - See also: about/see_also.md

theme:
  favicon: img/favicon.ico
  features:
    - instant
  icon:
    logo: fontawesome/solid/book-reader
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    accent: indigo
    primary: indigo
